_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 41
                - 51
                - 53
                - 55
                - 76
                - 77
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
arch:
    value: TGNN_degree_guided
augmented_features:
    value: []
batch_size:
    value: 4
clip_norm:
    value: null
clip_value:
    value: 1
dataset:
    value: Ego
degree:
    value: true
diffusion_dim:
    value: 64
diffusion_steps:
    value: 32
dp_rate:
    value: 0.1
empty_graph_sampler:
    value: empirical
epochs:
    value: 1
final_prob_edge:
    value:
        - 0.999999999999
        - 1e-12
final_prob_node:
    value:
        - 0.999999999999
        - 1e-12
gamma:
    value: 0.1
has_node_feature:
    value: false
log_home:
    value: ./wandb
loss_type:
    value: vb_ce_xt_prescribred_st
lr:
    value: 0.0001
max_degree:
    value: 99
milestones:
    value: []
momentum:
    value: 0.9
momentum_sqr:
    value: 0.999
noise_schedule:
    value: linear
norm:
    value: None
num_edge_classes:
    value: 2
num_generation:
    value: 64
num_heads:
    value:
        - 8
        - 8
        - 8
        - 8
        - 1
num_iter:
    value: 32
num_node_classes:
    value: 2
num_node_feat:
    value: null
optimizer:
    value: adam
parallel:
    value: null
parametrization:
    value: xt_prescribed_st
pin_memory:
    value: true
resume:
    value: null
sample_time_method:
    value: importance
seed:
    value: 0
warmup:
    value: null
